// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPfmMsAKOof_l9nWR7qKromceroomJqfQ',
    appId: '1:446266275381:web:a8f658b497d9363673e37c',
    messagingSenderId: '446266275381',
    projectId: 'devin-todo-app',
    authDomain: 'devin-todo-app.firebaseapp.com',
    storageBucket: 'devin-todo-app.firebasestorage.app',
    measurementId: 'G-CRZZBHWKGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdVY8f5EBygBWK56oehvBi_uZ9ygGnf0s',
    appId: '1:446266275381:android:df5e03e4fbcaf21773e37c',
    messagingSenderId: '446266275381',
    projectId: 'devin-todo-app',
    storageBucket: 'devin-todo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QZMQYl6DaYi_LSDZ8gRNrrlQvyC0Ci0',
    appId: '1:446266275381:ios:38a52d3a884d8a8173e37c',
    messagingSenderId: '446266275381',
    projectId: 'devin-todo-app',
    storageBucket: 'devin-todo-app.firebasestorage.app',
    iosClientId: '446266275381-5qh6gt5nptqaoc8r28t9ina01eitjhqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QZMQYl6DaYi_LSDZ8gRNrrlQvyC0Ci0',
    appId: '1:446266275381:ios:38a52d3a884d8a8173e37c',
    messagingSenderId: '446266275381',
    projectId: 'devin-todo-app',
    storageBucket: 'devin-todo-app.firebasestorage.app',
    iosClientId: '446266275381-5qh6gt5nptqaoc8r28t9ina01eitjhqa.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPfmMsAKOof_l9nWR7qKromceroomJqfQ',
    appId: '1:446266275381:web:71de139e2232810473e37c',
    messagingSenderId: '446266275381',
    projectId: 'devin-todo-app',
    authDomain: 'devin-todo-app.firebaseapp.com',
    storageBucket: 'devin-todo-app.firebasestorage.app',
    measurementId: 'G-0NGNFEQFX0',
  );
}
